version: "3.8"
name: 'cafeteria-mircoservice'
services:
  catalog-db:
    image: postgres:17-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  user-service-redis:
    image: redis:8.2-rc1-alpine
    container_name: user-service-redis
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 500m
