version: "3.8"
name: 'cafeteria-mircoservice'
services:
  catalog-db:
    image: postgres:17-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  user-service-redis:
    image: redis:8.2-rc1-alpine
    container_name: user-service-redis
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 500m

  cafeteria-service-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cafeteria-service-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    deploy:
      resources:
        limits:
          memory: 500m

  cafeteria-service-kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: cafeteria-service-kafka-1
    depends_on:
      - cafeteria-service-zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cafeteria-service-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cafeteria-service-kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    deploy:
      resources:
        limits:
          memory: 500m


  cafeteria-service-kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: cafeteria-service-kafka-2
    depends_on:
      - cafeteria-service-zookeeper
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: cafeteria-service-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cafeteria-service-kafka-2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    deploy:
      resources:
        limits:
          memory: 500m