name: kafka-service.yml


on:
  push:
    paths:
      - kafka-service/**
    branches:
      - '**'

  pull_request:
    paths:
      - kafka-service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./kafka-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login into Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cafeteria-kafka-service
